spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz?characterEncoding=utf8
    username: root
    password: 111111
    driver-class-name: com.mysql.jdbc.Driver
    
mybatis: 
  mapper-locations:
  - classpath:com/example/demo/mapper/*.xml
  type-aliases-package: com.example.demo.entity

server:
  port: 8010

logging.level.com.example.demo.mapper: debug
